Admin dashboard
Kaffe-diem/kaffediem pull request #48
Opened 2024-11-02 09:29 UTC by IldenH

Flere av knappene går til ingenting akkurat nå. #44 og #45 vil løse noe av det.

2024-11-03 09:45 UTC, kluvin commented
Kan vi avvente med å lage system for å endre meny? Jeg tror det er det /kitchen er? Design går fint, men det er lett å trakke i salaten med BL.

Det er et par ting som må tenkes på og testes ut i henhold til dataintegritet. Det kan hende vi er nødt til å endre datamodellen.

* Enums må kanskje ut i egen tabell
* Ting skal kanskje ikke slettes, men arkiveres. For eksempel er det Halloween neste år
* Hvis man også skal endre kategorier, så er man farlig nærme oss et CMS. Noe som gjør at Sanity for eksempel kunne vært et valg.
*

2024-11-03 12:15 UTC, IldenH commented
Jeg har endret navnet på `/edit-drinks` til `/edit-menu`. `/kitchen` tenker jeg er ipaden bak hvor man kan se bestillinger som må gjennomføres. Denne pr-en handler bare om å vise hvilke menyer som skal være tilgjengelig for ansatte.

[Sanity](https://www.sanity.io) virker veldig kult og jeg vil gjerne bruke det i en senere PR når vi implementerer at ansatte kan endre menyen og kategoriene i menyen.

2024-11-03 13:17 UTC, LilleAila commented
> [Sanity](https://www.sanity.io) virker veldig kult og jeg vil gjerne bruke det i en senere PR når vi implementerer at ansatte kan endre menyen og kategoriene i menyen.

Å bruke sanity virker veldig overkill for å gjøre noe så enkelt som å legge til og endre verdier i to collections, jeg ser ingen grunn til å legge til enda en dependency bare for det. Jeg kan heller bare implementere en enkel visning der man kan gjøre dette.

2024-11-04 12:27 UTC, kluvin commented
> > [Sanity](https://www.sanity.io) virker veldig kult og jeg vil gjerne bruke det i en senere PR når vi implementerer at ansatte kan endre menyen og kategoriene i menyen.
> 
> Å bruke sanity virker veldig overkill for å gjøre noe så enkelt som å legge til og endre verdier i to collections, jeg ser ingen grunn til å legge til enda en dependency bare for det. Jeg kan heller bare implementere en enkel visning der man kan gjøre dette.

Veldig godt poeng!

2024-11-05 20:47 UTC, LilleAila requested changes

2024-11-05 20:47 UTC, LilleAila commented on src/routes/admin/frontdesk/+page.server.ts
Denne filen bør flyttes ett nivå opp, til `/admin/+page.server.ts`. Formålet med den er å triggere server-side hooks, slik at vi garanterer at uautentiserte brukere blir redirectet til en ikke-admin side.

2024-11-06 07:41 UTC, LilleAila approved these changes

2024-11-06 07:42 UTC, merged