Laget av melding i display :)
Kaffe-diem/kaffediem pull request #62
Opened 2024-11-13 17:29 UTC by CarlAugust

VI trenger ideer til noe mer cheeky enn "laget av elevene fra ITK :)". Jeg brukte for lang tid for dette.

2024-11-13 18:43 UTC, kluvin commented
Det ser bra ut med den nye divideren, god ide!

<img width="1512" alt="bilde" src="https://github.com/user-attachments/assets/35c6e8bf-de19-4746-a612-8f39becc5da2">


Kanskje vi kan midtstille alt i 'footeren'? Selve QR koden ser litt out-of-place akkurat slik den er. Finpuss er ikke supernødvendig.

2024-11-14 06:38 UTC, LilleAila requested changes

2024-11-14 06:38 UTC, LilleAila commented on src/routes/display/+page.svelte
> +<div class="divider md:divider-vertical"></div>
Divideren bør nok være sammen med resten, i layout.

2024-11-14 06:38 UTC, LilleAila commented on src/routes/display/+page.svelte
> +<div class="h-4/6">
Kunne du brukt en grid med noe lignende `gris grid-cols-1 grid-rows-[2fr_1fr]` i som parent i layouten, heller enn å modifisere denne filen?

2024-11-14 06:38 UTC, LilleAila commented on src/routes/display/+layout.svelte
> +<div class="absolute bottom-0 left-0 hidden md:flex w-screen">
Denne trenger ikke å være posisjonert `absolute` hvis det er en parent grid som den kan følge.

2024-11-14 06:39 UTC, LilleAila requested changes

2024-11-14 06:39 UTC, LilleAila commented on src/routes/display/+layout.svelte
> +    <p>Laget av elevene fra ITK :) </p>
Kunne det stått heller noe slikt som
```suggestion
    <p>Laget av elever på skolen :) </p>
```

2024-11-14 11:09 UTC, kluvin commented on src/routes/display/+layout.svelte
> +<div class="absolute bottom-0 left-0 hidden md:flex w-screen">
til kontekst: det var meg som la absolute til da vi ikke hadde en grid tidligere.
den er ikke så nødvendig nå med ny seksjon.

2024-11-14 11:11 UTC, kluvin commented
Det kom plutselig mye inn her @CarlAugust, gi en lyd om du vil paire!

2025-01-10 19:46 UTC, IldenH commented
Lukker grunnet lite aktivitet. Kan åpnes igjen om det er interesse for featuren.

2025-01-10 19:46 UTC, closed without merging